In [1]:
import pandas as pd
!pip install sqlalchemy
!pip install psycopg2-binary

Requirement already satisfied: sqlalchemy in C:\Users\HP\anaconda3\Lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in C:\Users\HP\anaconda3\Lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: psycopg2-binary in C:\Users\HP\anaconda3\Lib\site-packages (2.9.13)

In [2]:
from sqlalchemy import create_engine, text

In [3]:
Database_url = "postgresql://neondb_owner:npg_qStXmZLBQ5A9@ep-wispy-sunset-axezqxvm-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

In [4]:
engine = create_engine(Database_url)

In [5]:
# Create Connection
engine = create_engine (
    Database_url,
    poolclass= None,
    connect_args= {
        'sslmode':'require',
        'connect_timeout':10
    }

)

# Test Connection
try:
    with engine.connect() as connection:
        result= connection.execute(text('SELECT 1'))
        print('Database response:', result.fetchone())
        print('Successful connection')

except Exception as e:
    print('Connection failed:',repr(e))

Database response: (1,)
Successful connection

In [6]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

table = pd.read_sql(query, engine)

table.head()

       table_name
0        bookings
1          guests
2          hotels
3         reviews
4  clean_bookings

### Load Data

In [7]:
# Load booking data
bookings = pd.read_sql(
    "SELECT * FROM bookings", engine
)

bookings.head()

,booking_id,guest_id,hotel_id,room_type,booking_channel,check_in_date,check_out_date,total_amount,stay_duration
0,1,6699,18,Suite,Direct Website,2025-05-25,2025-05-26,296.44,1
1,2,11380,23,Deluxe,Corporate Portal,2025-01-09,2025-01-13,483.56,4
2,3,4812,13,Executive,Travel Agent,2025-03-04,2025-03-06,415.59,2
3,4,982,12,Family Room,Airbnb,2026-03-06,2026-03-09,601.18,3
4,5,615,5,Deluxe,Expedia,2025-02-25,2025-03-02,603.85,5

In [8]:
# Load guest data
guests = pd.read_sql(
    "SELECT * FROM guests", engine
)

guests.head()

   guest_id customer_type loyalty_status               country  previous_stays
0         1       Leisure           None             Australia               0
1         2       Leisure           None               Germany               1
2         3      Business           Gold        United Kingdom               0
3         4        Family         Silver  United Arab Emirates               8
4         5     Corporate           None                France               0

In [9]:
hotels = pd.read_sql(
    "SELECT * FROM hotels", engine
)

hotels.head()

   hotel_id            hotel_name    location  star_rating  total_rooms
0         1  The Birmingham Grand  Birmingham            4          254
1         2   The London Heritage      London            5          234
2         3   The Oxford Boutique      Oxford            3          146
3         4  The Glasgow Heritage     Glasgow            3           84
4         5  Glasgow Metropolitan     Glasgow            4          214

In [10]:
reviews = pd.read_sql(
    "SELECT * FROM reviews", engine
)

reviews.head()

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral
1,2,2,11380,23,The room was nothing out of the ordinary for w...,4.0,2025-01-22,positive
2,3,3,4812,13,"Unfortunately, the pool was outdated — it clea...",1.9,2025-03-13,negative
3,4,4,982,12,We were disappointed that the neighborhood was...,2.2,2026-03-18,negative
4,5,5,615,5,The room service was standard hotel fare for w...,3.3,2025-03-03,neutral

In [11]:
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   booking_id       35000 non-null  int64
 1   guest_id         35000 non-null  int64
 2   hotel_id         35000 non-null  int64
 3   room_type        35000 non-null  object
 4   booking_channel  35000 non-null  object
 5   check_in_date    35000 non-null  object
 6   check_out_date   35000 non-null  object
 7   total_amount     35000 non-null  float64
 8   stay_duration    35000 non-null  int64
dtypes: float64(1), int64(4), object(4)
memory usage: 2.4+ MB

In [12]:
guests.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   guest_id        12000 non-null  int64
 1   customer_type   12000 non-null  object
 2   loyalty_status  5964 non-null   object
 3   country         12000 non-null  object
 4   previous_stays  12000 non-null  int64
dtypes: int64(2), object(3)
memory usage: 468.9+ KB

In [13]:
hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hotel_id     25 non-null     int64
 1   hotel_name   25 non-null     object
 2   location     25 non-null     object
 3   star_rating  25 non-null     int64
 4   total_rooms  25 non-null     int64
dtypes: int64(3), object(2)
memory usage: 1.1+ KB

In [14]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   review_id        35000 non-null  int64
 1   booking_id       35000 non-null  int64
 2   guest_id         35000 non-null  int64
 3   hotel_id         35000 non-null  int64
 4   review_text      35000 non-null  object
 5   rating_score     35000 non-null  float64
 6   review_date      35000 non-null  object
 7   sentiment_label  35000 non-null  object
dtypes: float64(1), int64(4), object(3)
memory usage: 2.1+ MB

In [15]:
bookings.isnull().mean()*100

booking_id         0.0
guest_id           0.0
hotel_id           0.0
room_type          0.0
booking_channel    0.0
check_in_date      0.0
check_out_date     0.0
total_amount       0.0
stay_duration      0.0
dtype: float64

In [16]:
guests.isnull().mean()*100

guest_id           0.0
customer_type      0.0
loyalty_status    50.3
country            0.0
previous_stays     0.0
dtype: float64

In [17]:
hotels.isnull().mean()*100

hotel_id       0.0
hotel_name     0.0
location       0.0
star_rating    0.0
total_rooms    0.0
dtype: float64

In [18]:
reviews.isnull().mean()*100

review_id          0.0
booking_id         0.0
guest_id           0.0
hotel_id           0.0
review_text        0.0
rating_score       0.0
review_date        0.0
sentiment_label    0.0
dtype: float64

In [19]:
## Handling missing values in guest table

guests['loyalty_status'] = guests['loyalty_status'].fillna('Unknown')

In [20]:
guests.isnull().mean()*100

guest_id          0.0
customer_type     0.0
loyalty_status    0.0
country           0.0
previous_stays    0.0
dtype: float64

In [21]:
## Merging all tables.


# Build master review dataset
rev_df = (
    reviews
    .merge(
        bookings,
        on=['booking_id', 'guest_id', 'hotel_id'],
        how='left'
    )
    .merge(
        guests,
        on='guest_id',
        how='left'
    )
    .merge(
        hotels,
        on='hotel_id',
        how='left'
    )
)

print(rev_df.shape)
rev_df.head()

(35000, 22)

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label,room_type,booking_channel,...,total_amount,stay_duration,customer_type,loyalty_status,country,previous_stays,hotel_name,location,star_rating,total_rooms
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral,Suite,Direct Website,...,296.44,1,Leisure,Unknown,France,4,The Aberdeen Grand,Aberdeen,4,118
1,2,2,11380,23,The room was nothing out of the ordinary for w...,4.0,2025-01-22,positive,Deluxe,Corporate Portal,...,483.56,4,Business,Gold,Germany,4,Nottingham Park Hotel,Nottingham,4,95
2,3,3,4812,13,"Unfortunately, the pool was outdated — it clea...",1.9,2025-03-13,negative,Executive,Travel Agent,...,415.59,2,Business,Unknown,Ireland,4,The London Boutique,London,4,231
3,4,4,982,12,We were disappointed that the neighborhood was...,2.2,2026-03-18,negative,Family Room,Airbnb,...,601.18,3,Leisure,Unknown,Nigeria,0,Manchester Metropolitan,Manchester,3,101
4,5,5,615,5,The room service was standard hotel fare for w...,3.3,2025-03-03,neutral,Deluxe,Expedia,...,603.85,5,Group,Unknown,United States,9,Glasgow Metropolitan,Glasgow,4,214

In [22]:
rev_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   review_id        35000 non-null  int64
 1   booking_id       35000 non-null  int64
 2   guest_id         35000 non-null  int64
 3   hotel_id         35000 non-null  int64
 4   review_text      35000 non-null  object
 5   rating_score     35000 non-null  float64
 6   review_date      35000 non-null  object
 7   sentiment_label  35000 non-null  object
 8   room_type        35000 non-null  object
 9   booking_channel  35000 non-null  object
 10  check_in_date    35000 non-null  object
 11  check_out_date   35000 non-null  object
 12  total_amount     35000 non-null  float64
 13  stay_duration    35000 non-null  int64
 14  customer_type    35000 non-null  object
 15  loyalty_status   35000 non-null  object
 16  country          35000 non-null  object
 17  previous_stays   35000 non-null  int64
 18  hotel_name       35000 non-null  object
 19  location         35000 non-null  object
 20  star_rating      35000 non-null  int64
 21  total_rooms      35000 non-null  int64
dtypes: float64(2), int64(8), object(12)
memory usage: 5.9+ MB

In [23]:
## Checking for Duplicates after merging

rev_df.duplicated().sum()

np.int64(0)

In [24]:
## Confirming abscence of duplicates
print(bookings['booking_id'].nunique())
print(reviews['booking_id'].nunique())

35000
35000

In [25]:
import os

# Define the folder path
folder_path = r"c:\Users\HP\OneDrive\Documents\AMDARI\Montra Hospitality Project\Notebook"

# Create the full save path for your new CSV file
save_path = os.path.join(folder_path, "merged_data.csv")

# Save the dataframe to the folder (index=False stops it from adding an extra column of numbers)
rev_df.to_csv(save_path, index=False)

print(f"File successfully saved to: {save_path}")

File successfully saved to: c:\Users\HP\OneDrive\Documents\AMDARI\Montra Hospitality Project\Notebook\merged_data.csv

##### Notes

- Tables were extracted from the database and inspected to identify matching columns and presence of missing values before merging them together.

- Identified missing values (greater than 50%) in loyalty_status column of the guests table was replaced by "unknown" as the column may be important in downline analysis.

- A left join on the reviews table was used to merge all the tables into one as the reviews table has matching columns in the other tables and the reviews table is the table of interest in sentiment analysis.